### ISSUE TITLE
Add tags for unfurlers?

### ISSUE THREAD

**Issue by freeatnet** [vaidehijoshi/better-code-reviews#2]
Hey @vaidehijoshi!

Saw the project on Twitter! It's pretty awesome, so I immediately shared it to relevant Slack teams. I noticed, however, that the link didn't get an awesome visual attachment representation it deserves. I think it might be because the page is missing some `og:title` and `og:image` meta-tags.

Would you be interested in having those added?

**Comment by vaidehijoshi** [comment]
yes! good catch, @freeatnet. that would be great, did you want to make a PR for that?

**Comment by freeatnet** [comment]
@vaidehijoshi For sure. Would you prefer per-page customizable tags or would using static tags in `source/layouts/layout.erb` work?

**Comment by vaidehijoshi** [comment]
I think a static tag in `layout.erb` would work perfectly 😸  thank you, @freeatnet!!

**Comment by vaidehijoshi** [comment]
This is looking good (in Slack, at least!).

<img width="665" alt="screen shot 2017-06-18 at 1 10 12 pm" src="https://user-images.githubusercontent.com/6921610/27263861-8319dfa6-5427-11e7-976f-43364907149f.png">

Great job, @freeatnet. Thanks for noticing and fixing this. And now I know how to do this myself in the future 😄
